name: cadusuario_frontend
description: Cadastro de usuários sistemas corporativos

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.13.1
  rxdart: ^0.26.0
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/btm.jpg

