//Strings
const CPF = 'CPF';
const NOME = 'Nome';
const EMAIL = 'Email';
const DATA_NASCIMENTO = 'Data de nascimento';
const SALVANDO = 'Salvando...';
const SALVAR = 'Salvar';
const FALHA = 'Falha';
const VALOR_INCORRETO = 'Valor incorreto';
const DIGITE_O_ID = 'Digite o ID';
const CADASTRO_USUARIO = 'Cadastro usuário';
const CONTEUDO = 'Content-Type';
const APLICACAO = 'application/json; charset=UTF-8';
const NIVEL = 'Nível';
const NIVEL_LOGADO = 'Nível Logado';
const SENHA = 'Senha';
const LOGIN = 'Login';
const ALTERAR_STATUS = 'Alterar status';
const USUARIOS_APROVADOS = 'Usuários aprovados';
const CADASTRAR_NOVO_USUARIO = 'Cadastrar novo usuário';
const USUARIOS_REPROVADOS = 'Usuários reprovados';
const PESQUISAR_USUARIO = 'Pesquisar usuário';
