const URL_API = 'http://192.168.100.88:9999';

const ENDPOINT_CADASTRO_USUARIO_PENDENTE = '$URL_API/usuario/listar/P';
const ENDPOINT_CADASTRO_USUARIO_APROVADO = '$URL_API/usuario/listar/A';
const ENDPOINT_CADASTRO_USUARIO_REPROVADO = '$URL_API/usuario/listar/R';

const ENDPOINT_CADASTRO_USUARIO = '$URL_API/usuario/';
const ENDPOINT_CADASTRO_USUARIO_ATUALIZAR = '$URL_API/usuario/atualizar';
const ENDPOINT_CADASTRO_USUARIO_ALTERAR_STATUS = '$URL_API/usuario/alterarstatus';
const ENDPOINT_CADASTRO_LOGIN = '$URL_API/login';